name: GitHub Actions Test

on:
  push:
    branches:
      - master
  
jobs:
  readme:
    name: README.md to PDF,HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          input_path: README.md
          output_dir: generated
          build_html: true
      - uses: actions/upload-artifact@v4
        with:
          name: readme
          path: generated
